from plot import plot
import matplotlib.pyplot as plt
from nltk.translate.bleu_score import SmoothingFunction, sentence_bleu

#compute BLEU-4 score
def compute_bleu(output, reference):
    """
    #The target word
    reference = 'variable'
    #The word generated by your model
    output = 'varable'
    """
    cc = SmoothingFunction()
    return sentence_bleu([reference], output,weights=(0.25, 0.25, 0.25, 0.25),smoothing_function=cc.method1)

print(compute_bleu('hellooo','hello'))